version: '3'
services:
    mysql-container:
        image: mysql:5.7
        container_name: mysql-container
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: transactions-db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
volumes:
    db-data: